name: Client CI Checks

on:
  push:
    branches: [main] # or staging, test]
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  client-checks:
    name: typescript check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1

    - name: Install dependencies
      run: bun install

    - name: Run Type Check
      run: |
        bun run check

    - name: Run Build
      run: bun run build